image: Visual Studio 2019
version: '2.1.0-unstable.{build}'

pull_requests:
  do_not_increment_build_number: true

before_build:
  - nuget restore Source/OxyPlot.Contrib.sln

build_script:
  - msbuild Source/OxyPlot.Contrib.sln "/p:Platform=Any CPU" "/p:Configuration=Release" "/p:Version=%APPVEYOR_BUILD_VERSION%"

artifacts:
  - path: '**/bin/Release/**/*.nupkg'
    name: packages

deploy:
  provider: NuGet
  server: https://www.myget.org/F/oxyplot/api/v2/package
  api_key:
    secure: 2GnqgfpkOUH6Umfn1WWlun0b021+QeInBXkgQOQfa4/wDOYHLT757rrjTsb0lmon
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: packages
